### ISSUE TITLE
support for container(type=<order|project>) bfabric (>= 10)

### ISSUE THREAD

**Issue by cpanse** [fgcz/bfabricShiny#12]
```{bash}
bfabric_list.py order id 4677
bfabric_list.py workunit orderid 4677
bfabric_list.py resource workunitid  174492
```

![screenshot 2018-11-23 at 11 28 54](https://user-images.githubusercontent.com/4901987/48938939-fd204380-ef12-11e8-9508-1e333f681f86.png)

**Comment by cpanse** [comment]
<img width="1526" alt="queue_generator_bfabric10_c" src="https://user-images.githubusercontent.com/4901987/91035727-bdfeb500-e606-11ea-8c6e-ba23ab6dbc0c.png">

**Comment by wolski** [comment]
Orders are supported  in the queue multiplexing demultiplexing.
