### ISSUE TITLE
generalize `getQCsample` and  `getHPLCparameter`

### ISSUE THREAD

**Issue by cpanse** [fgcz/bfabricShiny#16]
to enable that the shiny application can run on several sites
the methods 

[ ] https://github.com/cpanse/bfabricShiny/blob/84148c7bf37fc9dd9f511bd2a0b180f7c692fd46/R/ms_queue.R#L66

[ ] https://github.com/cpanse/bfabricShiny/blob/84148c7bf37fc9dd9f511bd2a0b180f7c692fd46/R/ms_queue.R#L83

should be given as argument from the shiny application.

**Comment by wolski** [comment]
Since now there is a method getHPLCparameter I am closing this issue
