### ISSUE TITLE
queue generator wish list [in German]

### ISSUE THREAD

**Issue by cpanse** [fgcz/bfabricShiny#9]
* Ob die Condition/das Grouping im Namen vorkommt oder nicht sollte waehlbar sein…. – es macht keinen Sinn wenn da keine Conditions sind bzw NA im Feld steht, weils kein LFQ sondern ein reines Protein ID Experiment ist dass da bei jedem Sample Namen hinten noch ***_N_A angehaengt wird. Muss das dann jedes mal manuell raushauen weils mir sonst nur den Namen kuenstlich verlaengert.

* Darf im Namen ein ‚-‚ drin sein? Dachte die muessten auch durch ‚_‘ ersetzt werden?

* Queue Reihenfolge zusaetzlich zu ‚default‘, ,random‘ etc sollte auch noch manuell machbar sein.

* So das Samples in der Reihenfolge in der Queue erscheinen in welcher ich sie anwaehle und nicht in der Reihenfolge der Sample ID’s... manchmal brauche ich eine spezielle Reihenfolge welche weder Random ist noch der Sample ID’s Reihenfolge entspricht. Wenn ich dann manuell in Excel alles wieder von Hand umstellen muss machts nicht viel Sinn.

**Comment by wolski** [comment]
All items are addressed in the current version of the Queue Generator. Therefore I am closing this issue.
